CREATE DATABASE sportbets_db;
GRANT ALL PRIVILEGES ON sportbets_db.* TO 'sportbets'@'localhost';

CREATE TABLE tbl_Ratios(
    `date` date NOT NULL,
    `matchID` int(11) NOT NULL,
	`r1` double DEFAULT NULL,
	`r2` double DEFAULT NULL,
	`r3` double DEFAULT NULL,
	`r4` double DEFAULT NULL,
	`r5` double DEFAULT NULL,
	`r6` double DEFAULT NULL,
	`r7` double DEFAULT NULL,
	`r8` double DEFAULT NULL,
	`r9` double DEFAULT NULL,
	`r10` double DEFAULT NULL,
	`r11` double DEFAULT NULL,
	`r12` double DEFAULT NULL,
	`r13` double DEFAULT NULL,
	`r14` double DEFAULT NULL,
	`r15` double DEFAULT NULL,
	`r16` double DEFAULT NULL,
	`r17` double DEFAULT NULL,
	`r18` double DEFAULT NULL,
	`r19` double DEFAULT NULL,
	`r20` double DEFAULT NULL,
	`r21` double DEFAULT NULL,
	`r22` double DEFAULT NULL,
	`r23` double DEFAULT NULL,
	`r24` double DEFAULT NULL,
	`r25` double DEFAULT NULL,
	`r26` double DEFAULT NULL,
	`r27` double DEFAULT NULL,
	`r28` double DEFAULT NULL,
	`r29` double DEFAULT NULL,
	`r30` double DEFAULT NULL,
	`r31` double DEFAULT NULL,
	`r32` double DEFAULT NULL,
	`r33` double DEFAULT NULL,
	`r34` double DEFAULT NULL,
	`r35` double DEFAULT NULL,
	`r36` double DEFAULT NULL,
	`r37` double DEFAULT NULL,
	`r38` double DEFAULT NULL,
	`r39` double DEFAULT NULL,
	`r40` double DEFAULT NULL,
	`r41` double DEFAULT NULL,
	`r42` double DEFAULT NULL,
	`r43` double DEFAULT NULL,
	`r44` double DEFAULT NULL,
	`r45` double DEFAULT NULL,
	`r46` double DEFAULT NULL,
	`r47` double DEFAULT NULL,
	`r48` double DEFAULT NULL,
	`r49` double DEFAULT NULL,
	`r50` double DEFAULT NULL,
	PRIMARY KEY (`date`,`matchID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE tbl_MatchInfo(
    `date` date NOT NULL,
    `time` datetime NOT NULL,
    `matchID` int(11) NOT NULL,
    `league` varchar(5) NOT NULL,
    `team_1` varchar(40) CHARACTER SET utf8 NOT NULL,
    `team_2` varchar(40) CHARACTER SET utf8 NOT NULL,
    `mbs` tinyint NOT NULL,
    `iy_goals_1` tinyint NOT NULL,
    `iy_goals_2` tinyint NOT NULL,
    `ms_goals_1` tinyint NOT NULL,
    `ms_goals_2` tinyint NOT NULL,
    `h1` tinyint NOT NULL,
    `h2` tinyint NOT NULL,
    `was_played` boolean NOT NULL DEFAULT 0,
	PRIMARY KEY (`date`,`matchID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE tbl_Results(
    `date` date NOT NULL,
    `matchID` int(11) NOT NULL,
	`r1` boolean NOT NULL DEFAULT 0,
	`r2` boolean NOT NULL DEFAULT 0,
	`r3` boolean NOT NULL DEFAULT 0,
	`r4` boolean NOT NULL DEFAULT 0,
	`r5` boolean NOT NULL DEFAULT 0,
	`r6` boolean NOT NULL DEFAULT 0,
	`r7` boolean NOT NULL DEFAULT 0,
	`r8` boolean NOT NULL DEFAULT 0,
	`r9` boolean NOT NULL DEFAULT 0,
	`r10` boolean NOT NULL DEFAULT 0,
	`r11` boolean NOT NULL DEFAULT 0,
	`r12` boolean NOT NULL DEFAULT 0,
	`r13` boolean NOT NULL DEFAULT 0,
	`r14` boolean NOT NULL DEFAULT 0,
	`r15` boolean NOT NULL DEFAULT 0,
	`r16` boolean NOT NULL DEFAULT 0,
	`r17` boolean NOT NULL DEFAULT 0,
	`r18` boolean NOT NULL DEFAULT 0,
	`r19` boolean NOT NULL DEFAULT 0,
	`r20` boolean NOT NULL DEFAULT 0,
	`r21` boolean NOT NULL DEFAULT 0,
	`r22` boolean NOT NULL DEFAULT 0,
	`r23` boolean NOT NULL DEFAULT 0,
	`r24` boolean NOT NULL DEFAULT 0,
	`r25` boolean NOT NULL DEFAULT 0,
	`r26` boolean NOT NULL DEFAULT 0,
	`r27` boolean NOT NULL DEFAULT 0,
	`r28` boolean NOT NULL DEFAULT 0,
	`r29` boolean NOT NULL DEFAULT 0,
	`r30` boolean NOT NULL DEFAULT 0,
	`r31` boolean NOT NULL DEFAULT 0,
	`r32` boolean NOT NULL DEFAULT 0,
	`r33` boolean NOT NULL DEFAULT 0,
	`r34` boolean NOT NULL DEFAULT 0,
	`r35` boolean NOT NULL DEFAULT 0,
	`r36` boolean NOT NULL DEFAULT 0,
	`r37` boolean NOT NULL DEFAULT 0,
	`r38` boolean NOT NULL DEFAULT 0,
	`r39` boolean NOT NULL DEFAULT 0,
	`r40` boolean NOT NULL DEFAULT 0,
	`r41` boolean NOT NULL DEFAULT 0,
	`r42` boolean NOT NULL DEFAULT 0,
	`r43` boolean NOT NULL DEFAULT 0,
	`r44` boolean NOT NULL DEFAULT 0,
	`r45` boolean NOT NULL DEFAULT 0,
	`r46` boolean NOT NULL DEFAULT 0,
	`r47` boolean NOT NULL DEFAULT 0,
	`r48` boolean NOT NULL DEFAULT 0,
	`r49` boolean NOT NULL DEFAULT 0,
	`r50` boolean NOT NULL DEFAULT 0,
	PRIMARY KEY (`date`,`matchID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE tbl_Coupons(
    `couponID` int(11) NOT NULL,
    `date` date NOT NULL,
    `matchID` int(11) NOT NULL,
	`r1` boolean NOT NULL DEFAULT 0,
	`r2` boolean NOT NULL DEFAULT 0,
	`r3` boolean NOT NULL DEFAULT 0,
	`r4` boolean NOT NULL DEFAULT 0,
	`r5` boolean NOT NULL DEFAULT 0,
	`r6` boolean NOT NULL DEFAULT 0,
	`r7` boolean NOT NULL DEFAULT 0,
	`r8` boolean NOT NULL DEFAULT 0,
	`r9` boolean NOT NULL DEFAULT 0,
	`r10` boolean NOT NULL DEFAULT 0,
	`r11` boolean NOT NULL DEFAULT 0,
	`r12` boolean NOT NULL DEFAULT 0,
	`r13` boolean NOT NULL DEFAULT 0,
	`r14` boolean NOT NULL DEFAULT 0,
	`r15` boolean NOT NULL DEFAULT 0,
	`r16` boolean NOT NULL DEFAULT 0,
	`r17` boolean NOT NULL DEFAULT 0,
	`r18` boolean NOT NULL DEFAULT 0,
	`r19` boolean NOT NULL DEFAULT 0,
	`r20` boolean NOT NULL DEFAULT 0,
	`r21` boolean NOT NULL DEFAULT 0,
	`r22` boolean NOT NULL DEFAULT 0,
	`r23` boolean NOT NULL DEFAULT 0,
	`r24` boolean NOT NULL DEFAULT 0,
	`r25` boolean NOT NULL DEFAULT 0,
	`r26` boolean NOT NULL DEFAULT 0,
	`r27` boolean NOT NULL DEFAULT 0,
	`r28` boolean NOT NULL DEFAULT 0,
	`r29` boolean NOT NULL DEFAULT 0,
	`r30` boolean NOT NULL DEFAULT 0,
	`r31` boolean NOT NULL DEFAULT 0,
	`r32` boolean NOT NULL DEFAULT 0,
	`r33` boolean NOT NULL DEFAULT 0,
	`r34` boolean NOT NULL DEFAULT 0,
	`r35` boolean NOT NULL DEFAULT 0,
	`r36` boolean NOT NULL DEFAULT 0,
	`r37` boolean NOT NULL DEFAULT 0,
	`r38` boolean NOT NULL DEFAULT 0,
	`r39` boolean NOT NULL DEFAULT 0,
	`r40` boolean NOT NULL DEFAULT 0,
	`r41` boolean NOT NULL DEFAULT 0,
	`r42` boolean NOT NULL DEFAULT 0,
	`r43` boolean NOT NULL DEFAULT 0,
	`r44` boolean NOT NULL DEFAULT 0,
	`r45` boolean NOT NULL DEFAULT 0,
	`r46` boolean NOT NULL DEFAULT 0,
	`r47` boolean NOT NULL DEFAULT 0,
	`r48` boolean NOT NULL DEFAULT 0,
	`r49` boolean NOT NULL DEFAULT 0,
	`r50` boolean NOT NULL DEFAULT 0,
	`won` boolean NOT NULL DEFAULT 0,
	PRIMARY KEY (`couponID`, `date`,`matchID`)
);


CREATE TABLE tbl_UserCoupon(
    `userID` int(11) NOT NULL,
    `couponID` int(11) NOT NULL,
    `start_date` date NOT NULL,
    `end_date` date NOT NULL,
	`won` boolean NOT NULL DEFAULT 0,
	`ratio` double DEFAULT NULL,
	PRIMARY KEY (`couponID`, `userID`)
);

